
export const serverFile = {
  MISSING_URL: "DB_URL is missing in .env file",
  NODE_VERSION: "Node version must be 20 or higher",
  CONNECTION: "Connection to the database was successful",
  ERROR: "Error connecting to the database",
  PORT: "Server is running on port",
  SERVER_ERROR: "Server error",
};
export const userMessage = {
  USER_CREATED: "User created successfully",
  USER_EXIST: "User already exists",
  USER_NOT_FOUND: "User not found",
  INVALID_CREDENTIALS: "Invalid email or password",
  OTP_SENT: "OTP sent to your email",
  OTP_INVALID: "Invalid OTP",
  INVALID_OTP:"Invalid OTP",
  OTP_NOT_FOUND: "OTP_NOT_FOUND",
  VERIFY_EMAIL:"Please verify your email before login",
  INVALID_TYPE:"Invalid OTP type",
  OTP_EXPIRED: "OTP has expired",
  OTP_VERIFIED: "OTP verified successfully",
  PASSWORD_RESET_SUCCESS: "Password reset successfully",
  PASSWORD_RESET_FAILED: "Failed to reset password",
  USER_UPDATED: "User updated successfully",
  USER_DELETED: "User deleted successfully",
  USER_LIST: "User list retrieved successfully",
  REQUIRED_FIELDS: "Name, email, and password are required",
  LOGIN_SUCCESS: "Login successful",
  LOGOUT_SUCCESS: "Logout successful",
  REQUIRED_TOKEN: "Refresh token required",
  INVALID_TOKEN: "token is not valid",
  NEW_TOKEN: "New access token generated",
  FETCH_PROFILE: "User profile fetched successfully",
  INCORRECT_PASSWORD: "Incorrect old password",
  CHANGE_PASSWORD: "Password changed successfully",
  REQUIRED: "idToken and provider are required.",
  SOCIAL_AUTH_FAIL: "Social authentication failed. Email or Social ID missing.",
  DEACTIVATE: "Your account has been deactivated by admin.",
  SOCIAL_LOGIN_SUCEES: "Logged in successfully via social authentication.",
  PROVIDER_NOT_SUPPORT:"`Provider is not supported yet."
};
export const authMessage = {
  USER_NOT_FOUND: "this user not found or inactive",
  INVALID: "token is not valid",
  UN_AUTH: "Unauthorize user",
};
export const TICKET_MESSAGE = {
  USER_NOT_FOUND: "You are not user",
  TICKET_CREATE: "Ticket create successfully",
  TICKET_NOT_FOUND: "Your Ticket not found",
  ACCESS_DENIED: "You are not acess",
  TICKET_CLOSE: "Ticket close successfully",
  TICKET_FETCHED: "Ticket fetched successfully",
  ALL_TICKET: "All ticket fetched successfully",
  TICKET_ASSIGN: "Ticket Assign Successfully",
  DASHBOARD: "dashBoard fetch successfully",
  STATUS: "change ticket status successfully",
  PRIORITY: "change ticket priority successfully",
  RE_ASSIGN_TICKET_ASSIGN: "Ticket reassigned successfully",
  UPDATE_TICKET_HISTORY: "Ticket history updated successfully",
  HISTORY_NOT_FOUND:"Ticket history not found",
  TICKET_HISTORY_FETCHED: "Ticket history fetched successfully",
  DELETE_TICKET_HISTORY: "History deleted successfully",
  AGENT_HISTORY: "Agent history fetched successfully",
  MESSAGE_CREATED: "Message created successfully",
  MESSAGE_FETCHED: "Message(s) fetched successfully",
  MESSAGE_NOT_FOUND: "Message not found",
  MESSAGE_DELETED: "Message deleted successfully",
  NOTIFICATION_ID: "Notification ID is required",
  NOTIFICATION_NOT_FOUND: "Notification not found",
  NOTIFICATION_SUCCESS: "Notification marked as read successfully",
  NOTIFICATION_FETCH: "Notifications fetched successfully",
  AGENT_ID: "Agent Id is required",
  AGENT_DASHBOARD: "Agent Dashboard Fetched Successfully",
  INVALID_STATUS: "Invalid status value. Use true or false.",
  NO_USER_FOUND: "User not found or update failed",
  NOTIFICATION_ENABLED:"Mobile notifications enabled successfully",
  NOTIFICATION_DISABLED: "Mobile notifications disabled successfully",
  STATUS_REQUIRED: "Status parameter is required (true/false)",
}
export const AGENT_MESSAGE = {
  AGENTS_LIST_FETCHED: "Agents list fetched successfully",
  AGENTS_LIST_NOT_FOUND: "No agents found",
}
export const DEPARTMENT_MESSAGE = {
  DEPARTMENTS_FETCHED: "Departments fetched successfully",
  DEPARTMENTS_NOT_FOUND: "No departments found",
}
