
export const serverFile = {
  MISSING_URL: "DB_URL is missing in .env file",
  NODE_VERSION: "Node version must be 20 or higher",
  CONNECTION: "Connection to the database was successful",
  ERROR: "Error connecting to the database",
  PORT: "Server is running on port",
  SERVER_ERROR: "Server error",
};
export const userMessage = {
  USER_CREATED: "User created successfully",
  USER_EXIST: "User already exists",
  USER_NOT_FOUND: "User not found",
  INVALID_CREDENTIALS: "Invalid email or password",
  OTP_SENT: "OTP sent to your email",
  OTP_INVALID: "Invalid OTP",
  PASSWORD_RESET_SUCCESS: "Password reset successfully",
  PASSWORD_RESET_FAILED: "Failed to reset password",
  USER_UPDATED: "User updated successfully",
  USER_DELETED: "User deleted successfully",
  USER_LIST: "User list retrieved successfully",
  REQUIRED_FIELDS: "Name, email, and password are required",
  LOGIN_SUCCESS: "Login successful",
  REQUIRED_TOKEN: "Refresh token required",
  INVALID_TOKEN: "token is not valid",
  NEW_TOKEN:"New access token generated",
};
export const authMessage = {
  USER_NOT_FOUND: "this user not found or inactive",
  INVALID: "token is not valid",
  UN_AUTH: "Unauthorize user",
};
export const TICKET_MESSAGE = {
  USER_NOT_FOUND: "You are not user",
  TICKET_CREATE: "Ticket create successfully",
  TICKET_NOT_FOUND: "Your Ticket not found",
  ACCESS_DENIED: "You are not acess",
  TICKET_CLOSE: "Ticket close successfully",
  TICKET_FETCHED: "Ticket fetched successfully",
  ALL_TICKET: "All ticket fetched successfully",
  TICKET_ASSIGN: "Ticket Assign Successfully",
  DASHBOARD: "dashBoard fetch successfully",
  STATUS: "change ticket status successfully",
  PRIORITY: "change ticket priority successfully",
  RE_ASSIGN_TICKET_ASSIGN: "Ticket reAssign Assign Successfully",
  UPDATE_TICKET_HISTORY: "Ticket history updated successfully",
  HISTORY_NOT_FOUND:"Ticket history not found",
  TICKET_HISTORY_FETCHED: "Ticket history fetched successfully",
  DELETE_TICKET_HISTORY: "History deleted successfully",
  AGENT_HISTORY: "Agent history fetched successfully",
  MESSAGE_CREATED: "Message created successfully",
  MESSAGE_FETCHED: "Message(s) fetched successfully",
  MESSAGE_NOT_FOUND: "Message not found",
  MESSAGE_DELETED: "Message deleted successfully",
}
