import "dotenv/config";
import express from "express";
import mongoose from "mongoose";
import http from "http";
import startServer from "./app.js";
import erroHandler from "../src/middleweare/errorHandler.js";
import userRoutes from "../src/routes/userRoutes.js";
const app = express();
app.use(express.json());
app.use("/uploads", express.static("uploads"));
app.use("/api/users", userRoutes);
app.use(erroHandler);
startServer(app);